# Generated by Django 4.2.7 on 2023-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('image', models.ImageField(default='defaul.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='mediauser',
            name='image',
            field=models.ImageField(default='defaul.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
